### ISSUE TITLE
Zoomer can get out time range

### ISSUE THREAD

**Issue by thomasfillon** [wavesjs/ui#1]
With large translation or large zoom-out factor , the zoomer can get out the audio Buffer time range and give graph.xScale.domain() out of the original xDomain.

See the issue here : https://jsfiddle.net/thomasfillon/6hqLwb6p/

A possible workaround  is to constraint the graph.xScale.domain() not to get out the original xDomain given by graph.xDomain() . Here is the function that checks the limits and fixes the xScale values:

    function lockZoomOut(graph) {
      var xScaleDomain = graph.xScale.domain();
      var xDomain = graph.xDomain();

      if (xScaleDomain[0] < xDomain[0] || xScaleDomain[1] > xDomain[1]) {
        var min = Math.max(xDomain[0], xScaleDomain[0]);
        var max = Math.min(xDomain[1], xScaleDomain[1]);
    
        graph.xScale.domain([min, max]);
      }
    }

See implementation here (improved by @b-ma ) :  https://jsfiddle.net/j2g2scm7/165/

**Comment by b-ma** [comment]
Hey Thomas,

I prepared an integration of your patch in the `lockZoomOut` branch.
The modifications are quite simples : 
- define an option : https://github.com/wavesjs/ui/blob/lockZoomOut/es6/core/timeline.js#L14
- your patch : https://github.com/wavesjs/ui/blob/lockZoomOut/es6/core/timeline.js#L225
- and the call to the patch in the xZoom method : https://github.com/wavesjs/ui/blob/lockZoomOut/es6/core/timeline.js#L211

the final result can be seen here : http://jsfiddle.net/uspsak37/
It looks like it works quite nicely, PR or something ?

**Comment by thomasfillon** [comment]
Hi Benjamin,

It looks great to me and you could merge into master branch as far as I'm concern ! Many thanks 

I guess it would be complicated to make the option an option for the zoomer and not from the timeline ?

**Comment by b-ma** [comment]
Hey,

About your question, if we add the patch in the `zoomer` instead of the `timeline`, it implies two options in my opinion : 
- if we want the process to be transparent for the user of the library, this means the `zoomer` has to know the `timeline` in some way, which is something I'm not sure we do want, as the initial idea was to keep these two modules as much separated as possible.
- the second option, which may be interesting, would be to simply add the patch as a helper method of the `zoomer`, and consume it in a way close to your first proposal : 

```
zoomer.on('mousemove', function (e) {
    graph.xZoom(e);
    zoomer.lockZoomOut(graph);
    graph.update();
})
````

Actually this may be a better option, I should discuss it also with @ouhouhsami to have another point of view, what would be your opinion as a user of the library ? 
Many thx

**Comment by thomasfillon** [comment]
Ok, thx, I get your point about keeping the two modules separated. It makes sense and gives more flexibility for consuming the zoomer output. So, it may be better to keep it like this.

**Comment by b-ma** [comment]
Hey Thomas,

After discussion with @ouhouhsami , we will keep the patch in the timeline, as it looks like it is its responsibility. So, the patch is now merged into the master branch, use as follow : 
```
var graph = timeline({ lockZoomOutOnInitialDomain: true })
```
Here is a working example based on your initial fiddle : http://jsfiddle.net/uspsak37/2/

Many thanks for the contribution !

**Comment by ouhouhsami** [comment]
A quick remark: the key label lockZoomOutOnInitialDomain seems not appropriate. It should not mention Zoom and Out, may be just lockOnInitialDomain, or lockMoveOnInitialDomain, or ... something clever.
