### ISSUE TITLE
surface.js questions

### ISSUE THREAD

**Issue by echo66** [wavesjs/ui#11]
Greetings! I have two questions regarding [surface.js](https://github.com/wavesjs/ui/blob/develop/es6/interactions/surface.js):

1) Why are you using "body.addEventListener" and "body.removeEventListener" instead of "this.el.addEventListener" and "this.el.removeEventListener"? After all, you want to capture actions on "this.el" DOM element instead of "body".

2) Is there any specific reason for you to only emit "mousemove" events after a "mousedown"?

**Comment by b-ma** [comment]
Hey,

short answers about your questions:

1. the `mousemove` and `mouseup` events are bound to the window because it feels a more natural way of interacting with the timeline. If the events are bound to the timeline's `svg` elements it creates frustrating user experience when zooming for example.
2. it's a choice, because we don't have seen any use case yet were we need the `mousemove` without the `mousedown` first.

In a more general perspective, we tried to decouple all the interactions (through the `EventSource` and `AbstractTimelineState` abstractions) to allow final users to implement their own interactions. In this perspective, the `Surface` should mostly be thought as a default interaction proposal. It is not implemented yet but a way to override these defaults or to add your own interaction source (MIDI, ...) is planned.

**Comment by echo66** [comment]
Thanks Benjamin!

Hope to see this new version at WAC, it seems promissing. :+1:
